apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: MPI
metadata:
  name: test-mpi
  namespace: default
spec:
  job:
    completions: 6
    parallelism: 6
    template:
      spec:
        containers:
        - image: continuse/mpich:v3
          imagePullPolicy: IfNotPresent
          name: mpi
          command: ["mpirun", "-n", "6", "hostname"]
          resources:
            requests:
              cpu: "200m"