language: go

go_import_path: github.com/kubernetes-incubator/kube-arbitrator

install:
  - ./hack/install-etcd.sh
  - go get -u github.com/golang/lint/golint

before_script:
  - export PATH=`pwd`/third_party/etcd:${PATH}
  - export TEST_LOG_LEVEL=4

script:
  - make verify
  - make
  - make run-test
