apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    component: controller
    tier: control-plane
  name: kube-queuejob-ctrl
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: controller
        tier: control-plane
        version: second
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - touch /tmp/healthy; /opt/kube-queuejob-ctrl --scheduler-name kube-batchd; rm -f /tmp/healthy
        image: kubearbitrator/queuejob-ctrl:v0.1
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        name: kube-queuejob-ctrl
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts: []
      hostNetwork: false
      hostPID: false
      volumes: []
